import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
     name: "Jade Plant",
     description: "",
     price: "₹399 ",
     rating: "4.5",
     review: "32",
    discountPrice:"₹299",
    off:"(25% OFF)",
     imgSrc: "../assets/jadePlant.jpg",
     inStock: "",
     categoryName: "Grown-Plants",
     type: "indoor-plant"
  },
  {
    _id: uuid(),
    name: "Broken Heart Plant",
    description: "",
    price: "₹499 ",
    rating: "4.5",
    review: "12",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/brokenHeart.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "indoor-plant"
  },
  {
    _id: uuid(),
    name: "Peace Lily Plant",
    description: "",
    price: "₹499 ",
    rating: "4.5",
    review: "4",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/peaceLilly.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "indoor-plant"
  },
  {
    _id: uuid(),
    name: "Chlorophytum Spider Plant",
    description: "",
    price: "₹399",
    rating: "4.5",
    review: "31",
   discountPrice:"₹299",
   off:"(25% OFF)",
    imgSrc: "../assets/spiderPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "outdoor-plant"
  },
  {
    _id: uuid(),
    name: "Ficus Prestige",
    description: "",
    price: "₹499 ",
    rating: "4.5",
    review: "11",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/ficusPrestige.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "outdoor-plant"
  },
  {
    _id: uuid(),
    name: "Ajwain Plant",
    description: "",
    price: "₹499",
    rating: "4.5",
    review: "3",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/ajwainPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "outdoor-plant"
  },
  {
    _id: uuid(),
    name: "Betel Leaf Plant",
    description: "",
    price: "₹499",
    rating: "4.5",
    review: "21",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/betelLeaf.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "high-maintanace"
  },
  {
    _id: uuid(),
    name: "Anthurium Red Plant",
    description: "",
    price: "₹799",
    rating: "4.5",
    review: "9",
   discountPrice:" ₹699",
   off:"(13% OFF)",
    imgSrc: "../assets/anthuriumPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "high-maintanance"
  },
  {
    _id: uuid(),
    name: "Snake Plant",
    description: "",
    price: "₹499",
    rating: "4.5",
    review: "8",
   discountPrice:" ₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/snakePlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "low-maintanance"
  },
  {
    _id: uuid(),
    name: "ZZ Plant",
    description: "",
    price: "₹699",
    rating: "4.5",
    review: "21",
   discountPrice:" ₹599",
   off:"(14% OFF)",
    imgSrc: "../assets/zzPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "low-maintanance"
  },
  {
    _id: uuid(),
    name: "Haworthia Cooperi Fleshy",
    description: "",
    price: "₹499",
    rating: "4.5",
    review: "12",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/haworthiaPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "decor-plant"
  },
  {
    _id: uuid(),
    name: "Crassula Ovata Plant",
    description: "",
    price: "₹399",
    rating: "4.5",
    review: "8",
   discountPrice:"₹299",
   off:"(25% OFF)",
    imgSrc: "../assets/crassullaPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "decor-plant"
  },
  {
    _id: uuid(),
    name: "Ixora (Rugmini) Plant",
    description: "",
    price: "₹749",
    rating: "4.5",
    review: "4",
   discountPrice:"₹699",
   off:"(7% OFF)",
    imgSrc: "../assets/ixoraPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "flowering-plant"
  },
  {
    _id: uuid(),
    name: "Kalanchoe Plant",
    description: "",
    price: "₹499",
    rating: "4.5",
    review: "23",
   discountPrice:"₹399",
   off:"(20% OFF)",
    imgSrc: "../assets/kalanchoePlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "flowering-plant"
  },
  {
    _id: uuid(),
    name: "Adenium Red Plant",
    description: "",
    price: "₹899",
    rating: "4.5",
    review: "31",
   discountPrice:"₹799",
   off:"(11% OFF)",
    imgSrc: "../assets/adeniumPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "flowering-plant"
  },
  {
    _id: uuid(),
    name: "Bamboo Palm Plant",
    description: "",
    price: "₹699",
    rating: "4.5",
    review: "32",
   discountPrice:"₹599",
   off:"(14% OFF)",
    imgSrc: "../assets/bambooPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "air-purifying"
  },
  {
    _id: uuid(),
    name: "Rubber Plant",
    description: "",
    price: "₹699",
    rating: "4.5",
    review: "32",
   discountPrice:"₹599",
   off:"(14% OFF)",
    imgSrc: "../assets/rubberPlant.jpg",
    inStock: "",
    categoryName: "Grown-Plants",
    type: "air-purifying"
  },
  {
    _id: uuid(),
    name: "Apple Ceramic Pot",
    description: "",
    price: "₹300",
    rating: "4",
    review: "3",
   discountPrice:"₹195",
   off:"(35% OFF)",
    imgSrc: "../assets/appleCeramic.jpg",
    inStock: "",
    categoryName: "Plant-Pots",
    type: ""
  },
  {
    _id: uuid(),
    name: "Star Ceramic Pot",
    description: "",
    price: "₹400",
    rating: "3.5",
    review: "4",
   discountPrice:"₹225",
   off:"(44% OFF)",
    imgSrc: "../assets/starCeramic.jpg",
    inStock: "",
    categoryName: "Plant-Pots",
    type: ""
  },
  {
    _id: uuid(),
    name: "Pipe Ceramic Pot ",
    description: "",
    price: "₹395",
    rating: "3.5",
    review: "11",
   discountPrice:"₹265",
   off:"(33% OFF)",
    imgSrc: "../assets/pipeCeramic.jpg",
    inStock: "",
    categoryName: "Plant-Pots",
    type: ""
  },
  {
    _id: uuid(),
    name: "Watermelon Ceramic Planter",
    description: "",
    price: "₹400",
    rating: "4",
    review: "12",
   discountPrice:"₹295",
   off:"(26% OFF)",
    imgSrc: "../assets/watermelonCeramic.jpg",
    inStock: "",
    categoryName: "Plant-Pots",
    type: ""
  },
  {
    _id: uuid(),
    name: "Long Handle Cultivator",
    description: "",
    price: "₹245",
    rating: "4.5",
    review: "21",
   discountPrice:"220",
   off:"(10%)",
    imgSrc: "../assets/cultivatorTool.jpg",
    inStock: "",
    categoryName: "Garden-Tools",
    type: ""
  },
  {
    _id: uuid(),
    name: "Pebbles Coloured - 1 kg",
    description: "",
    price: "₹510",
    rating: "4",
    review: "11",
   discountPrice:"₹275",
   off:"(46% OFF)",
    imgSrc: "../assets/pebbleTool.jpg",
    inStock: "",
    categoryName: "Garden-Tools",
    type: ""
  },
  {
    _id: uuid(),
    name: "Transplanter Plastic Sleeve",
    description: "",
    price: "₹485",
    rating: "3.5",
    review: "11",
   discountPrice:"₹285",
   off:"(41% OFF)",
    imgSrc: "../assets/seeveTool.jpg",
    inStock: "",
    categoryName: "Garden-Tools",
    type: ""
  },
  {
    _id: uuid(),
    name: "Double Side Rake & Trowel",
    description: "",
    price: "₹295",
    rating: "3",
    review: "22",
   discountPrice:"280",
   off:"(5%)",
    imgSrc: "../assets/doubleToll.jpg",
    inStock: "",
    categoryName: "Garden-Tools",
    type: ""
  },
];

